---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: VBox
platforms:
  - name: bionicInstance
    box: ubuntu/bionic64
    interfaces:
      - network_name: forwarded_port
        guest: 80
        host: 8082
  - name: focalInstance
    box: ubuntu/focal64
    interfaces:
      - network_name: forwarded_port
        guest: 80
        host: 8083
provisioner:
  name: ansible
verifier:
  name: testinfra
