---
# tasks file for main redmine
- name: install mariadb
  import_tasks: mariadb.yml

- name: install rvm
  import_tasks: rvm.yml

- name: clone redmine
  import_tasks: redmine.yml
  
- name: execute bundler
  import_tasks: bundler.yml
  
- name: configure puma
  import_tasks: puma.yml
  
- name: install nginx
  import_tasks: nginx.yml

- name: configure iptables
  import_tasks: iptables.yml



