---
# tasks file for puma
- name: add the user nginx to redmine group
  user:
    name: nginx
    shell: /bin/bash
    groups: redmine
    append: yes
    
- name: create socket directory
  file:
    path: /var/www/redmine/sockets
    state: directory
    owner: redmine
    group: redmine
    
- name: create pids directory
  file:
    path: /var/www/redmine/pids
    state: directory
    owner: redmine
    group: redmine
    
- name: set service file
  template: 
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service 
    
- name: create puma config 
  copy:
    dest: /var/www/redmine/config/puma.rb
    owner: redmine
    group: redmine
    content: |
      #!/usr/bin/env puma

      # RAILS_ENV=production bundle exec puma -C ./config/puma.rb

      application_path = '/var/www/redmine'
      directory application_path
      environment 'production'
      pidfile "#{application_path}/pids/puma.pid"
      state_path "#{application_path}/pids/puma.state"
      stdout_redirect "#{application_path}/log/puma.stdout.log", "#{application_path}/log/puma.stderr.log"
      bind "unix://#{application_path}/sockets/puma.sock"
  notify: 
  -  restart puma

- name: flush handlers
  meta: flush_handlers
      
