---
# tasks file for redmine
- name: create user redmine and add it to rvm group
  user:
    name: redmine
    shell: /bin/bash
    groups: rvm
    append: yes

- name: check if redmine folder exists
  stat:
    path: /var/www/redmine/
  register: check_redmine_folder
  
- name: clone redmine project
  git:
    repo: 'https://github.com/redmine/redmine'
    dest: /var/www/redmine/
    version: "{{redmine_version}}"
  when: check_redmine_folder.stat.exists != True

- name: set database file
  template: 
    src: database.yml.j2 
    dest: /var/www/redmine/config/database.yml

- name: install libmysqlclient 
  apt:
    name: libmysqlclient-dev
    update_cache: yes
  

    

