---
# tasks file for mariadb
- name: Install required packages
  apt:
    name: software-properties-common, mariadb-server, mariadb-client, python3-pip
    update_cache: yes

- name: Install pymysql
  pip:
    name: pymysql
    state: present

- name: Update MariaDB root password
  community.mysql.mysql_user: 
    login_user: root
    login_password: ''
    login_host: 127.0.0.1
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root 
    host: localhost 
    password: "{{mariadb_root_password}}"

- name: Set ~/.my.cnf file
  template: 
    src: my.cnf.j2 
    dest: /root/.my.cnf 
    mode: 0600
 
- name: Delete anonymous MySQL user
  community.mysql.mysql_user: 
    name: "" 
    host: 127.0.0.1 
    state: absent
    
- name: Delete Hostname based MySQL user
  community.mysql.mysql_user: 
    name: root 
    host: "{{ansible_nodename}}" 
    state: absent

- name: Remove MySQL test database
  community.mysql.mysql_db: 
    name: test 
    state: absent
