---
# handlers file for redmine
- name: generate secret token
  command: bundle exec rake generate_secret_token
  args:
    chdir: /var/www/redmine
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: migrate database
  command: bundle exec rake db:migrate
  args:
    chdir: /var/www/redmine
  environment:
    RAILS_ENV: production
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: load default data
  command: bundle exec rake redmine:load_default_data
  args:
    chdir: /var/www/redmine
  environment:
    RAILS_ENV: production   
    REDMINE_LANG: es 
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
    
- name: restart puma
  service:
    daemon_reload: yes
    name: puma
    state: restarted
    enabled: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
