---
# handlers file for redmine
- name: install bundler
  command: bash -lc "gem install bundler"
  
- name: generate secret token
  command: bundle exec rake generate_secret_token
  args:
    chdir: /usr/share/redmine/

- name: migrate database
  command: bundle exec rake db:migrate
  args:
    chdir: /usr/share/redmine/
  environment:
    RAILS_ENV: production

- name: load default data
  command: bundle exec rake redmine:load_default_data
  args:
    chdir: /usr/share/redmine/
  environment:
    RAILS_ENV: production   
    REDMINE_LANG: es 

- name: enable redmine virtual host
  command: a2ensite redmine.conf

- name: reload apache2
  service:
    name: apache2
    state: reloaded
